pythonlib: more error for script.task.parse_interface
Trying to avoid any possible unhandled excpetion when parsing modules. This helps modules which are parsed on startup to construct menus (toolboxes).

Motivation is an the following reported (http://lists.osgeo.org/pipermail/grass-dev/2015-May/074999.html) error:
  ParseError: not well-formed (invalid token): line 17, column 19
which occured in parse_interface during _expandRuntimeModules in toolboxes.py